# Generated by Django 6.0.6 on 2026-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='draft',
            field=models.TextField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO'),
        ),
    ]
