# Generated by Django 6.0.6 on 2026-07-17 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisement_favorites_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='ad',
            new_name='advertisement',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'advertisement')},
        ),
    ]
