# Generated by Django 6.0.6 on 2026-07-17 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_rename_ad_favorite_advertisement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='advertisement',
            new_name='adv',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'adv')},
        ),
    ]
